core/urls.py
from django.contrib import admin
from django.urls import path, include
from loan_products import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'), # first page (Home page)
    path('register/', views.register, name='register'), # second page (Register page)
    path('login/', views.user_login, name='login'), # third page (Login page)
    path('logout/', views.user_logout, name='logout'), # url to view that logs out a user
    path('loan-products/', views.show, name='loan_products'), # forth page (View data from the db page)
    path('loan-products/new/', views.new_loan_product, name='new_loan_product'), # fifth page (Create new data page)
    path('loan-products/edit/<int:id>/', views.edit, name='edit_loan_product'), # six page (Update data page)
    path('loan-products/delete/<int:id>/', views.destroy, name='delete_loan_product'), # url to view that deletes an item
    path('set-session/', views.set_session_token, name='set_session_token'),
    path('session/', views.get_session_token, name='get_session_token'),
    path('members/', views.view_members, name='view_members'),
    path('dashboard/', views.dashboard, name='dashboard'),
    #loan routes
    path('loans/', include('loans.urls')),
]

loan_products/models.py
from django.db import models


class LoanProduct(models.Model):
    INTEREST_TYPE_CHOICES = [
        ('fixed', 'Fixed'),
        ('variable', 'Variable'),
    ]

    TERM_PERIOD_CHOICES = [
        ('days', 'Days'),
        ('weeks', 'Weeks'),
        ('months', 'Months'),
        ('years', 'Years'),
    ]

    STATUS_CHOICES = [
        ('active', 'Active'),
        ('inactive', 'Inactive'),
    ]

    id = models.AutoField(primary_key=True)
    product_name = models.CharField(max_length=100)
    product_description = models.TextField()
    minimum_amount = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    maximum_amount = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    interest_rate_per_year = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    interest_type = models.CharField(max_length=10, choices=INTEREST_TYPE_CHOICES, default='fixed')
    max_term = models.IntegerField(default=0)
    term_period = models.CharField(max_length=10, choices=TERM_PERIOD_CHOICES, default='months')
    late_payment_penalties = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='active')

    class Meta:
        db_table = "loan_product"

loan_products/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from loan_products.models import LoanProduct
from django.contrib.auth.models import User

class LoanProductForm(forms.ModelForm):
    class Meta:
        model = LoanProduct
        fields = "__all__"


class CustomUserCreationForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True, help_text='Required. Enter your first name.')
    last_name = forms.CharField(max_length=30, required=True, help_text='Required. Enter your last name.')
    phone_number = forms.CharField(max_length=15, required=True, help_text='Required. Enter your phone number.')
    gender = forms.ChoiceField(choices=[('M', 'Male'), ('F', 'Female')], required=True, help_text='Required. Select your gender.')
 
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'phone_number', 'gender', 'password1', 'password2']

loan_products/views.py
from django.shortcuts import render, redirect, get_object_or_404
from loan_products.forms import LoanProductForm
from loan_products.models import LoanProduct
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ValidationError
from django.contrib import messages
from django.http import HttpResponseForbidden, HttpResponse, HttpResponseRedirect
from datetime import datetime, timedelta
from user_details.models import UserDetail
from loans.models import Loan
from django.db import models

# Create your views here.
def home(request):
    return render(request,'home.html')

@login_required(login_url='/login/')
def new_loan_product(request):
    if request.method == "POST":
        form = LoanProductForm(request.POST)
        if form.is_valid():
            try:
                # Save the form data to the database
                form.save()
                return redirect('/loan-products/')
            except ValidationError as e:
                # Handle validation errors
                messages.error(request, f"Validation error: {', '.join(e)}")
            except Exception as e:
                # Handle other exceptions
                messages.error(request, f"An error occurred: {e}")
    else:
        form = LoanProductForm()

    return render(request, 'new_loan_product.html', {'form': form})

def show(request):
    loan_products = LoanProduct.objects.all()
    user_details = UserDetail.objects.get(user_id=request.user)
    return render(request,"show.html",{'loan_products':loan_products, 'user_details': user_details})

@login_required(login_url='/login/')
def edit(request, id):
    # Retrieve the loan product or return a 404 response
    loan_product = get_object_or_404(LoanProduct, id=id)


    if request.method == "POST":
        form = LoanProductForm(request.POST, instance=loan_product)
        if form.is_valid():
            try:
                form.save()
                messages.success(request, "Loan product updated successfully.")
                return redirect("/loan-products/")
            except Exception as e:
                messages.error(request, f"An error occurred: {e}")
    else:
        form = LoanProductForm(instance=loan_product)

    return render(request, 'edit.html', {'loan_product': loan_product, 'form': form})

@login_required(login_url='/login/')
def destroy(request, id):
    loan_product = LoanProduct.objects.get(id=id)
    loan_product.delete()
    return redirect("/loan-products/")

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            user_details = {
                'first_name': request.POST.get('first_name'),
                'last_name': request.POST.get('last_name'),
                'phone_number': request.POST.get('phone_number'),
                'gender': request.POST.get('gender'),
                'user_id': user
            }
            UserDetail.objects.create(**user_details)
            return redirect('loan_products')
    else:
        form = UserCreationForm()
    return render(request, 'register.html', {'form': form})

def user_login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            login(request, form.get_user())
            return redirect('loan_products')
    else:
        form = AuthenticationForm()
    return render(request, 'login.html', {'form': form})


def user_logout(request):
    logout(request)
    return redirect('home')

def set_session_token(request):
    if not request.user.is_authenticated:
        return HttpResponseForbidden()
    response = HttpResponse()
    session_token = request.POST.get('session_token')
    response = HttpResponseRedirect('/')
    expires = datetime.now() + timedelta(days=7)
    response.set_cookie('sessionid', session_token, expires=expires, path='/')
    return response

def get_session_token(request):
    session_token = request.COOKIES.get('sessionid')
    if not request.user.is_authenticated:
        return HttpResponseForbidden()
    if session_token:
        return render(request, 'authorized.html', {'session_token': session_token})

    return render(request, 'authorized.html', {'session_token': 'No session token set'})

@login_required(login_url='/login/')
def view_members(request):
    users = UserDetail.objects.all()
    return render(request, 'members.html', {'users': users})

@login_required(login_url='/login/')
def dashboard(request):
    user_details = UserDetail.objects.get(user_id=request.user)
    loans = Loan.objects.all()

    if user_details.is_admin:
        template = 'admin_dashboard.html'
        users_count = UserDetail.objects.count()
        loan_products_count = LoanProduct.objects.count()
        loans_count = Loan.objects.count()
        total_principal = Loan.objects.aggregate(models.Sum('applied_amount'))['applied_amount__sum']
        total_interest = Loan.objects.aggregate(models.Sum('total_interest_paid'))['total_interest_paid__sum']
        
        context = {
            'users_count': users_count,
            'loan_products_count': loan_products_count,
            'loans_count': loans_count,
            'total_principal': total_principal,
            'total_interest': total_interest,
            'loans': loans,
        }
    else:
        loans = Loan.objects.filter(borrower=request.user)
        template = 'user_dashboard.html'
        context = {
            'user_details': user_details,
            'user_loans': loans
        }
    
    return render(request, template, context)

loan_products/templates/admin_dashboard.html
{% extends 'layout.html' %}

{% block title %}Admin Dashboard{% endblock %}

{% block content %}

  <div class="row mb-3">
    <div class="col">
      <h2>Admin Dashboard</h2>
    </div>
  </div>

  <div class="row">
    <div class="col-md-3">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Users</h5>
          <p class="card-text">{{ users_count }}</p>
        </div>
      </div>
    </div>
    <div class="col-md-3">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Loan Products</h5>
          <p class="card-text">{{ loan_products_count }}</p>
        </div>
      </div>
    </div>
    <div class="col-md-3">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Loans Given</h5>
          <p class="card-text">{{ loans_count }}</p>
        </div>
      </div>
    </div>
    <div class="col-md-3">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Total Principal</h5>
          <p class="card-text">{{ total_principal }}</p>
        </div>
      </div>
    </div>
    <div class="col-md-3">
      <div class="card my-2">
        <div class="card-body">
          <h5 class="card-title">Total Interest</h5>
          <p class="card-text">{{ total_interest }}</p>
        </div>
      </div>
    </div>
  </div>


    <div class="row mt-4">
        <div class="col">
          <h5>Loans:</h5>
          {% if loans %}
            <table class="table">
                <thead>
                    <tr>
                        <th>Loan ID</th>
                        <th>Amount</th>
                        <th>Loan Product</th>
                        <th>Status</th>
                        <!-- Add more table headers for other loan details -->
                    </tr>
                </thead>
                <tbody>
                    {% for loan in loans %}
                        <tr>
                            <td>{{ loan.id }}</td>
                            <td>{{ loan.applied_amount }}</td>
                            <td>{{ loan.loan_product.product_name }}</td>
                            <td>{{ loan.status }}</td>
                            <!-- Add more table cells for other loan details -->
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
          {% else %}
            <p>No loans found.</p>
          {% endif %}
        </div>
      </div>
    
    
  </div>

  <!-- Add additional sections or information based on your requirements -->



{% endblock %}

loan_products/templates/authorized.html
{% extends 'layout.html' %}

{% block title %}Loan Management System{% endblock %}

{% block content %}
<div class="row mb-3">
    <div class="col">
      <h1>User Session</h1>
    </div>
    <p>
        {{ session_token }}
    </p>
  </div>

  <form action="{% url 'set_session_token' %}" method="post">
    <!-- set session token -->
    {% csrf_token %}
    <div class="form-group">
      <label for="id_username">Set session token:</label>
      <input type="text" name="session_token" id="id_username" class="form-control" required>
      <button class="btn btn-success">Set session</button>
    </div>
  </form>
  {% endblock %}

loan_products/templates/edit.html
{% extends 'layout.html' %}

{% block title %}Edit Loan Product - Your Site{% endblock %}

{% block content %}
  <div class="row mb-3">
    <div class="col">
      <h1>Edit Loan Product</h1>
    </div>
  </div>

  <form method="post" action="{% url 'edit_loan_product' loan_product.id %}">
    {% csrf_token %}
    
    <div class="form-group">
      <label for="id_product_name">Product Name:</label>
      <input type="text" name="product_name" id="id_product_name" class="form-control" value="{{ loan_product.product_name }}" required>
    </div>
    
    <div class="form-group">
      <label for="id_product_description">Product Description:</label>
      <textarea name="product_description" id="id_product_description" class="form-control" required>{{ loan_product.product_description }}</textarea>
    </div>
    
    <div class="form-group">
      <label for="id_minimum_amount">Minimum Amount:</label>
      <input type="number" name="minimum_amount" id="id_minimum_amount" class="form-control" value="{{ loan_product.minimum_amount }}" required>
    </div>
    
    <div class="form-group">
      <label for="id_maximum_amount">Maximum Amount:</label>
      <input type="number" name="maximum_amount" id="id_maximum_amount" class="form-control" value="{{ loan_product.maximum_amount }}" required>
    </div>
    
    <div class="form-group">
      <label for="id_interest_rate_per_year">Interest Rate:</label>
      <input type="number" name="interest_rate_per_year" id="id_interest_rate_per_year" class="form-control" value="{{ loan_product.interest_rate_per_year }}" required>
    </div>
    
    <div class="form-group">
      <label for="id_interest_type">Interest Type:</label>
      <select name="interest_type" id="id_interest_type" class="form-control" required>
        <option value="fixed" {% if loan_product.interest_type == 'fixed' %}selected{% endif %}>Fixed</option>
        <option value="variable" {% if loan_product.interest_type == 'variable' %}selected{% endif %}>Variable</option>
      </select>
    </div>
    
    <div class="form-check">
      <input type="checkbox" name="mortgage_amortization" id="id_mortgage_amortization" class="form-check-input" {% if loan_product.mortgage_amortization %}checked{% endif %}>
      <label for="id_mortgage_amortization" class="form-check-label">Mortgage Amortization</label>
    </div>
    
    <div class="form-group">
      <label for="id_max_term">Max Term:</label>
      <input type="number" name="max_term" id="id_max_term" class="form-control" value="{{ loan_product.max_term }}" required>
    </div>
    
    <div class="form-group">
      <label for="id_term_period">Term Period:</label>
      <select name="term_period" id="id_term_period" class="form-control" required>

        <option value="days" {% if loan_product.term_period == 'days' %}selected{% endif %}>Days</option>
        <option value="weeks" {% if loan_product.term_period == 'weeks' %}selected{% endif %}>Weeks</option>
        <option value="months" {% if loan_product.term_period == 'months' %}selected{% endif %}>Months</option>
        <option value="years" {% if loan_product.term_period == 'years' %}selected{% endif %}>Years</option>
      </select>
    </div>
    
    <div class="form-group">
      <label for="id_late_payment_penalties">Late Payment Penalties:</label>
      <input type="text" name="late_payment_penalties" id="id_late_payment_penalties" class="form-control" value="{{ loan_product.late_payment_penalties }}" required>
    </div>
    
    <div class="form-group">
      <label for="id_status">Status:</label>
      <select name="status" id="id_status" class="form-control" required>
        <option value="active" {% if loan_product.status == 'active' %}selected{% endif %}>Active</option>
        <option value="inactive" {% if loan_product.status == 'inactive' %}selected{% endif %}>Inactive</option>
      </select>
    </div>
    
    <div class="d-flex my-3 gap-2">
      <button type="submit" class="btn btn-success mr-2">Update</button>
      <a class="btn btn-secondary" href="{% url 'loan_products' %}">Done</a>
    </div>
  </form>
  
{% endblock %}

loan_products/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Loan management system{% endblock %}</title>
    <!-- Add Bootstrap CDN links here -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400&display=swap" rel="stylesheet">

    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% load static %}

</head>

<style>
    body{
        font-family: 'Poppins', sans-serif;
    }
</style>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light mx-auto px-2 py-4">
    <a class="navbar-brand" href="#">LoanMe</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse w-100" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link"  class="nav-link text-primary" href="{% url 'home' %}">Home</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a  class="nav-link " href="{% url 'dashboard' %}">Dashboard</a>
            </li>
            {% if user_details.is_admin %}
            <li class="nav-item">
                <a class="nav-link " href="{% url 'view_members' %}">Members</a>
            </li>
            {% endif %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Loan Products
                </a>

                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="{% url 'loan_products' %}">View Loan Products</a></li>
                    {% if user.is_authenticated %}
                    {% if user_details.is_admin %}
                    <li><a class="dropdown-item" href="{% url 'new_loan_product' %}">Add New Loan Products</a></li>
                    {% endif %}
                    {% endif %}
                </ul>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Loans
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="{% url 'all_loans' %}">View Loans</a></li>
                    {% if user.is_authenticated %}
                    <li><a class="dropdown-item" href="{% url 'apply_for_loan' %}">Apply for loan</a></li>
                    {% endif %}
                </ul>
            </li>
            <li class="nav-item text-primary">
                <a href="#" class="nav-link text-primary">
                    Welcome {{ request.user }}
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-danger" href="{% url 'logout' %}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link text-success" href="{% url 'login' %}">Login</a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>

<div class="container-fluid px-5 mt-4">
<div class="row">
  <div class="col-md-6">

    <img src="{% static 'images/Login.jpeg' %}" style="height: 50vh;" width="90%"  alt="">
  </div>
  <div class="col-md-6">
    <div class="jumbotron">
      <h1 class="display-4">Welcome to the LoanMe Loan Management System</h1>
      <p class="lead">This system helps people manage their loans efficiently.</p>
      <hr class="my-4">
      <p>Track your loan products, apply for new loans, and manage your financial resources with ease.</p>
    </div>
  
    <div class="row">
      <div class="col-md-6">
        <h2>Features</h2>
        <ul>
          <li>View and manage your existing loan products.</li>
          <li>Apply for new loan products.</li>
          <li>Efficiently track your financial resources.</li>
        </ul>
      </div>
      <div class="col-md-6">
        <h2>Get Started</h2>
        <p>If you are a new user, <a href="{% url 'register' %}">register here</a> to create an account. If you already have an account, <a href="{% url 'login' %}">log in</a> to access your loan management dashboard.</p>
      </div>
    </div>
  </div>
</div>
<p class="text-center my-4" style= >
  <!-- copyright -->
For support call 077837382892
</p>
<p class="text-center text-primary">
  WhatsApp, Twitter, Facebook,
</p>
<p class="text-center my-4" style= >
  <!-- copyright -->
  &copy; {{ year }}  Loan Management System. All rights reserved.
</p>
</div>
</body>
</html>

loan_products/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Loan Management system{% endblock %}</title>
    <!-- Add Bootstrap CDN links here -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400&display=swap" rel="stylesheet">

    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}

</head>

<style>
    body{
        font-family: 'Poppins', sans-serif;
    }
</style>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light mx-auto px-2 py-4">
    <a class="navbar-brand" href="#">LoanMe</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse w-100" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link"  class="nav-link text-primary" href="{% url 'home' %}">Home</a>
            </li>

            {% if user.is_authenticated %}
            <li class="nav-item">
              <a  class="nav-link " href="{% url 'dashboard' %}">Dashboard</a>
            </li>
            {% if user_details.is_admin %}
            <li class="nav-item">
                <a class="nav-link " href="{% url 'view_members' %}">Members</a>
            </li>
            {% endif %}
            {% endif %}

            {% if user.is_authenticated %}

          
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Loan Products
                </a>

                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="{% url 'loan_products' %}">View Loan Products</a></li>
                    {% if user.is_authenticated %}
                    {% if user_details.is_admin %}
                    <li><a class="dropdown-item" href="{% url 'new_loan_product' %}">Add New Loan Products</a></li>
                    {% endif %}
                    {% endif %}
                </ul>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Loans
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="{% url 'all_loans' %}">View Loans</a></li>
                    {% if user.is_authenticated %}
                    <li><a class="dropdown-item" href="{% url 'apply_for_loan' %}">Apply for loan</a></li>
                    {% endif %}
                </ul>
            </li>
            <li class="nav-item text-primary">
                <a href="#" class="nav-link text-primary">
                    Welcome {{ request.user }}
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-danger" href="{% url 'logout' %}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link text-success" href="{% url 'login' %}">Login</a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>

<div class="container mt-4">
    {% block content %}{% endblock %}
</div>
</body>
</html>

loan_products/templates/new_loan_product.html
{% extends 'layout.html' %}

{% block title %}Add New Loan Product - Your Site{% endblock %}

{% block content %}
  <div class="row mb-3">
    <div class="col">
      <h1>Add New Loan Product</h1>
    </div>
  </div>

  <form method="post" action="{% url 'new_loan_product' %}">
    {% csrf_token %}
    
    <div class="form-group">
      <label for="id_product_name">Product Name:</label>
      <input type="text" name="product_name" id="id_product_name" class="form-control" required>
    </div>
    
    <div class="form-group">
      <label for="id_product_description">Product Description:</label>
      <textarea name="product_description" id="id_product_description" class="form-control" required></textarea>
    </div>
    
    <div class="form-group">
      <label for="id_minimum_amount">Minimum Amount:</label>
      <input type="number" name="minimum_amount" id="id_minimum_amount" class="form-control" required>
    </div>
    
    <div class="form-group">
      <label for="id_maximum_amount">Maximum Amount:</label>
      <input type="number" name="maximum_amount" id="id_maximum_amount" class="form-control" required>
    </div>
    
    <div class="form-group">
      <label for="id_interest_rate_per_year">Interest Rate:</label>
      <input type="number" name="interest_rate_per_year" id="id_interest_rate_per_year" class="form-control" required>
    </div>
    
    <div class="form-group">
      <label for="id_interest_type">Interest Type:</label>
      <select name="interest_type" id="id_interest_type" class="form-control" required>
        <option value="fixed">Fixed</option>
        <option value="variable">Variable</option>
      </select>
    </div>
  
    <div class="form-group">
      <label for="id_max_term">Loan Period:</label>
      <input type="number" name="max_term" id="id_max_term" class="form-control" required>
    </div>
    
    <div class="form-group">
      <label for="id_term_period">Term Period:</label>
      <select name="term_period" id="id_term_period" class="form-control" required>
        <option value="days">Days</option>
        <option value="weeks">Weeks</option>
        <option value="months">Months</option>
        <option value="years">Years</option>
      </select>
    </div>
    
    <div class="form-group">
      <label for="id_late_payment_penalties">Late Payment Penalties:</label>
      <input type="number" name="late_payment_penalties" id="id_late_payment_penalties" class="form-control" required>
    </div>
    
    <div class="form-group">
      <label for="id_status">Status:</label>
      <select name="status" id="id_status" class="form-control" required>
        <option value="active">Active</option>
        <option value="inactive">Inactive</option>
      </select>
    </div>
    
    <div class="d-flex my-3 gap-2">
      <button type="submit" class="btn btn-success mr-2">Save</button>
      <a class="btn btn-secondary" href="{% url 'loan_products' %}">Cancel</a>
    </div>
  </form>
  
{% endblock %}

loan_products/templates/register.html
{% extends 'layout.html' %}

{% block title %}Register{% endblock %}

{% block content %}
  <div class="row mb-3">
    <div class="col">
      <h2>Register</h2>
    </div>
  </div>

  <form method="post" action="{% url 'register' %}" class="col-md-6">
    {% csrf_token %}
    {% if form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
      {{ form.non_field_errors.as_text }}
    </div>
  {% endif %}

        <!-- Additional Fields for User Details -->
        <div class="form-group">
          <label for="id_first_name">First Name:</label>
          <input type="text" name="first_name" id="id_first_name" class="form-control" required>
        </div>
        <div class="form-group">
          <label for="id_last_name">Last Name:</label>
          <input type="text" name="last_name" id="id_last_name" class="form-control" required>
        </div>
        <div class="form-group">
          <label for="id_username">Username:</label>
          <input type="text" name="username" id="id_username" class="form-control" required>
          {% if form.username.errors %}
            <small class="text-danger">{{ form.username.errors.0 }}</small>
          {% endif %}
        </div>
        <div class="form-group">
          <label for="id_phone_number">Phone Number:</label>
          <input type="text" name="phone_number" id="id_phone_number" class="form-control" required>
        </div>
        <div class="form-group">
          <label for="id_gender">Gender:</label>
          <select name="gender" id="id_gender" class="form-control" required>
            <option value="M">Male</option>
            <option value="F">Female</option>
          </select>
        </div>
    

    <div class="form-group">
      <label for="id_password1">Password:</label>
      <input type="password" name="password1" id="id_password1" class="form-control" required>
      {% if form.password1.errors %}
        <small class="text-danger">{{ form.password1.errors.0 }}</small>
      {% endif %}
    </div>
    <div class="form-group">
      <label for="id_password2">Confirm Password:</label>
      <input type="password" name="password2" id="id_password2" class="form-control" required>
      {% if form.password2.errors %}
        <small class="text-danger">{{ form.password2.errors.0 }}</small>
      {% endif %}
    </div>
    <button type="submit" class="btn btn-success my-2">Register</button>
  </form>
{% endblock %}