core/urls.py
from django.contrib import admin
from django.urls import path, include
from loan_products import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'), # first page (Home page)
    path('register/', views.register, name='register'), # second page (Register page)
    path('login/', views.user_login, name='login'), # third page (Login page)
    path('logout/', views.user_logout, name='logout'), # url to view that logs out a user
    path('loan-products/', views.show, name='loan_products'), # forth page (View data from the db page)
    path('loan-products/new/', views.new_loan_product, name='new_loan_product'), # fifth page (Create new data page)
    path('loan-products/edit/<int:id>/', views.edit, name='edit_loan_product'), # six page (Update data page)
    path('loan-products/delete/<int:id>/', views.destroy, name='delete_loan_product'), # url to view that deletes an item
    path('set-session/', views.set_session_token, name='set_session_token'),
    path('session/', views.get_session_token, name='get_session_token'),
    path('members/', views.view_members, name='view_members'),
    path('dashboard/', views.dashboard, name='dashboard'),
    #loan routes
    path('loans/', include('loans.urls')),
]

loans/urls.py
from loans import views
from django.urls import path

urlpatterns = [
    path('', views.all_loans, name='all_loans'),
    path('apply/', views.apply_for_loan, name='apply_for_loan'),
    path('<int:loan_id>/', views.loan_detail, name='loan_detail'),
    path('<int:loan_id>/approval/', views.loan_approval, name='loan_approval'),
    path('<int:loan_id>/repayment/', views.create_loan_repayment, name='create_loan_repayment'),
    path('<int:loan_id>/repayments/<int:repayment_id>/delete/', views.delete_repayment, name='delete_repayment'),
]

loans/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import User
from loan_products.models import LoanProduct

class Loan(models.Model):
    LOAN_STATUS_CHOICES = [
        ('approved', 'Approved'),
        ('pending', 'Pending'),
        ('rejected', 'Rejected'),
    ]

    borrower = models.ForeignKey(User, on_delete=models.CASCADE)
    loan_product = models.ForeignKey(LoanProduct, on_delete=models.CASCADE)
    status = models.CharField(max_length=20, choices=LOAN_STATUS_CHOICES, default='pending')
    loan_date = models.DateField()
    applied_amount = models.DecimalField(max_digits=10, decimal_places=2)
    total_principal_paid = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    total_interest_paid = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    total_penalties_paid = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    due_amount = models.DecimalField(max_digits=10, decimal_places=2, blank=True, default=0.00)
    late_payment_penalties = models.DecimalField(max_digits=5, decimal_places=2, default=0.00)
    attachment = models.FileField(upload_to='loan_attachments/', null=True, blank=True)
    approved_date = models.DateField(blank=True, null=True, default=None)
    approved_by =  models.ForeignKey(User, on_delete=models.CASCADE,related_name='approved_by', blank=True, null=True)
    description = models.TextField(blank=True)
    remarks = models.TextField(blank=True)

    def __str__(self):
        return f'{self.borrower.username} - {self.loan_product.product_name}'

    class Meta:
        db_table = "loans"


class LoanRepayment(models.Model):
    loan = models.ForeignKey(Loan, on_delete=models.CASCADE)
    repayment_date = models.DateField()
    principal_paid = models.DecimalField(max_digits=10, decimal_places=2)
    interest_paid = models.DecimalField(max_digits=10, decimal_places=2)
    penalties_paid = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    remarks = models.TextField(blank=True)

    def __str__(self):
        return f"Repayment for Loan {self.loan.id} on {self.repayment_date}"
    
    class Meta:
        db_table = "loan_repayments"

loans/forms.py
# forms.py
from django import forms
from .models import Loan, LoanRepayment
from loan_products.models import LoanProduct

class LoanApplicationForm(forms.ModelForm):
    class Meta:
        model = Loan
        fields = ['loan_product', 'applied_amount', 'description']


    def clean(self):
        cleaned_data = super().clean()
        loan_product = cleaned_data.get("loan_product")
        applied_amount = cleaned_data.get("applied_amount")

        if loan_product and (applied_amount < loan_product.minimum_amount or applied_amount > loan_product.maximum_amount):
            raise forms.ValidationError("Applied amount must be within the allowed range.")

        return cleaned_data

class LoanApprovalForm(forms.Form):
    APPROVAL_CHOICES = [
        ('approved', 'Approved'),
        ('rejected', 'Rejected'),
    ]

    approval_status = forms.ChoiceField(choices=APPROVAL_CHOICES, widget=forms.RadioSelect)
    remarks = forms.CharField(widget=forms.Textarea, required=False)

class LoanRepaymentForm(forms.ModelForm):
    class Meta:
        model = LoanRepayment
        fields = ['principal_paid', 'interest_paid', 'penalties_paid', 'remarks','repayment_date']

loans/views.py
from django.shortcuts import render, redirect,get_object_or_404
from .models import Loan, LoanRepayment  # Assuming your Loan model is named Loan
from django.contrib.auth.decorators import login_required
from loan_products.models import LoanProduct
from user_details.models import UserDetail
from datetime import datetime, timedelta
from decimal import Decimal
from .forms import LoanApplicationForm, LoanApprovalForm, LoanRepaymentForm  # Assuming you have a LoanApplicationForm

@login_required(login_url='/login/')
def apply_for_loan(request):
    if request.method == 'POST':
        form = LoanApplicationForm(request.POST)
        if form.is_valid():
            loan = form.save(commit=False)
            loan.status = 'Pending'  # Set the initial status
            loan.borrower = request.user
            loan.loan_date = datetime.now()
            loan.save()
            return redirect('all_loans')  # Redirect to a success page
    else:
        form = LoanApplicationForm()
    
    loan_products = LoanProduct.objects.all()

    return render(request, 'apply_for_loan.html', {'form': form, 'loan_products': loan_products})

@login_required(login_url='/login/')
def all_loans(request):
    loans = []
    user_details = UserDetail.objects.get(user_id=request.user)
    if user_details.is_admin:
        loans = Loan.objects.all()
    else:
        loans = Loan.objects.filter(borrower=request.user)
    return render(request, 'all_loans.html', {'loans': loans, user_details: user_details})

@login_required(login_url='/login/')
def loan_detail(request, loan_id):
    user_details = UserDetail.objects.get(user_id=request.user)
    loan = get_object_or_404(Loan, id=loan_id)
    # collateral = Collateral.objects.filter(loan=loan).first()  # Assuming a one-to-one relationship


     # Retrieve the loan product based on the provided ID
    loan_product = LoanProduct.objects.get(pk=loan.loan_product.id)

    # Calculate the repayment schedule
    repayment_schedule = calculate_repayment_schedule(loan_product, loan.applied_amount, loan.loan_date)
    repayments = LoanRepayment.objects.filter(loan=loan).order_by('repayment_date')


    context = {
        'loan': loan,
        'repayment_schedule': repayment_schedule,
        'repayments': repayments,
        'user_details': user_details,
    }



    return render(request, 'loan_detail.html', context)

def loan_approval(request, loan_id):
    loan = get_object_or_404(Loan, id=loan_id)

    if request.method == 'POST':
        form = LoanApprovalForm(request.POST)
        if form.is_valid():
            loan.status = form.cleaned_data['approval_status']
            loan.approved_date = datetime.now()
            loan.approved_by = request.user  # Assuming you're using User authentication
            loan.remarks = form.cleaned_data['remarks']
            loan.save()
            return redirect('all_loans') # Redirect to home or another page after approval

    else:
        form = LoanApprovalForm()

    return render(request, 'loan_approval.html', {'loan': loan, 'form': form})


def calculate_repayment_schedule(loan_product, loan_amount, loan_date):
    # Extract relevant details from the loan product
    interest_rate = loan_product.interest_rate_per_year / 100
    term_period = loan_product.term_period
    loan_amount = Decimal(loan_amount)
    installment_count = loan_product.max_term

    # Calculate monthly interest rate
    monthly_interest_rate = interest_rate / 12

    # Calculate monthly installment using the formula for monthly loan payment
    monthly_installment = (loan_amount * monthly_interest_rate) / (1 - (1 + monthly_interest_rate)**(-installment_count))

    # Initialize repayment schedule list
    repayment_schedule = []

    # Calculate remaining balance and interest for each installment
    remaining_balance = loan_amount
    for installment in range(1, installment_count + 1):
        interest_payment = remaining_balance * monthly_interest_rate
        principal_payment = monthly_installment - interest_payment
        remaining_balance -= principal_payment

        # Append installment details to the schedule
        installment_date = loan_date + timedelta(days=(int(loan_product.max_term) * installment))
        repayment_schedule.append({
            'installment_number': installment,
            'installment_date': installment_date,
            'principal_payment': round(principal_payment),
            'interest_payment': round(interest_payment),
            'remaining_balance': round(remaining_balance),
        })

    return repayment_schedule



def create_loan_repayment(request, loan_id):
    loan = get_object_or_404(Loan, id=loan_id)

    if request.method == 'POST':
        form = LoanRepaymentForm(request.POST)
        if form.is_valid():
            repayment = form.save(commit=False)
            repayment.loan = loan
            repayment.save()

            # Update loan details
            loan.total_principal_paid += repayment.principal_paid
            loan.total_interest_paid += repayment.interest_paid
            loan.save()
            loan.due_amount = loan.applied_amount - loan.total_principal_paid
            loan.save()

            return redirect('loan_detail', loan_id=loan.id)
    else:
        form = LoanRepaymentForm()

    return redirect('loan_detail', loan_id=loan.id)

def delete_repayment(request, loan_id, repayment_id):
    loan_repayment = get_object_or_404(LoanRepayment, id=repayment_id, loan__id=loan_id)

    loan_repayment.delete()
        # You may want to update the cumulative value of all payments here

    return redirect('loan_detail', loan_id=loan_id)

loans/templates/all_loans.html
<!-- all_loans.html -->
{% extends 'layout.html' %}

{% block title %}All Loans {% endblock %}

{% block content %}
  <div class="row mb-3">
    <div class="col-md-8">
      <h1>All Loans</h1>
    </div>
    <div class="col-md-4">
      <a href="{% url 'apply_for_loan' %}" class="btn btn-primary">
        Apply For Loan
      </a>
    </div>
  </div>

  <div class="table-responsive">
    <table class="table">
        <thead>
            <tr>
                <th>Borrower</th>
                <th>Loan Product</th>
                <th>Amount Requested</th>
                <th>Status</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for loan in loans %}
                <tr>
                    <td>{{ loan.borrower }}</td>
                    <td>{{ loan.loan_product.product_name }}</td>
                    <td>{{ loan.applied_amount }}</td>
                    <td>{{ loan.status }}</td>
                    <td>
                        <a class="btn btn-primary" href="{% url 'loan_detail' loan.id %}">View</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}

loans/templates/apply_for_loan.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}Apply for Loan - Your Site{% endblock %}

{% block content %}
<div class="row">
  <div class="col-md-6">    <img src="{% static 'images/Apply.png' %}" style="height: 50vh;" width="90%"  alt="">
  </div>
  <div class="col-md-6">
    <div class="row mb-3">
      <div class="col">
        <h1>Apply for Loan</h1>
      </div>
    </div>
  
    <form method="post" action="{% url 'apply_for_loan' %}">
      {% csrf_token %}
      
      <div class="mb-3">
        <label for="loan_product">Loan Product:</label>
        <select class="form-select" name="loan_product" required>
          <option value="">Select Loan Product</option>
          {% for loan_product in loan_products %}
            <option value="{{ loan_product.id }}">{{ loan_product.product_name }}</option>
          {% endfor %}
        </select>
      </div>
  
      <div class="mb-3">
        <label for="applied_amount">Requested Amount:</label>
        <input type="number" class="form-control" name="applied_amount" required>
      </div>
  
      <div class="mb-3">
        <label for="description">Reason for request:</label>
        <textarea class="form-control" name="description" rows="3" required></textarea>
      </div>
  
      <div class="mb-3">
        <label for="remarks">Collateral:</label>
        <textarea class="form-control" name="remarks" rows="3"></textarea>
      </div>
  
      <div class="d-flex my-3 gap-2">
        <button type="submit" class="btn btn-success">Apply</button>
        <a class="btn btn-secondary" href="{% url 'all_loans' %}">Cancel</a>
      </div>
    </form>
    
  </div>
</div>

{% endblock %}

loans/templates/loan_detail.html
{% extends 'layout.html' %}

{% block title %}Loan Details - Your Site{% endblock %}

{% block content %}
    <div class="container mt-5">
        <h1>Loan Details</h1>

        <!-- Nav tabs -->
        <ul class="nav nav-tabs mt-4" id="myTabs" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" id="loan-details-tab" data-bs-toggle="tab" href="#loan-details" role="tab" aria-controls="loan-details" aria-selected="true">Loan Details</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="approval-tab" data-bs-toggle="tab" href="#approval" role="tab" aria-controls="approval" aria-selected="false">Approval</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="collateral-tab" data-bs-toggle="tab" href="#collateral" role="tab" aria-controls="collateral" aria-selected="false">Repayment schedule</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="repayments-tab" data-bs-toggle="tab" href="#repayments" role="tab" aria-controls="repayments" aria-selected="false">Repayments</a>
            </li>
          
        </ul>

        <!-- Tab content -->
        <div class="tab-content mt-3">
            <!-- Loan Details Tab -->
            <div class="tab-pane fade show active" id="loan-details" role="tabpanel" aria-labelledby="loan-details-tab">
                <div class="row mt-4">
                    <div class="col-md-12">
                      <div class="table-responsive">
                        <table class="table table-striped ">
                            <tbody>
                                <tr>
                                    <td>Borrower:</td>
                                    <td>{{ loan.borrower }}</td>
                                    <td>Loan ID:</td>
                                    <td>{{ loan.id }}</td>
                                </tr>
                                <tr>
                                    <td>Loan Product:</td>
                                    <td>{{ loan.loan_product.product_name }}</td>
                                    <td>Applied Amount:</td>
                                    <td>{{ loan.applied_amount }}</td>
                                </tr>
                                <tr>
                                    <td>Status:</td>
                                    <td>{{ loan.status }}</td>
                                    <td>Total Principal Paid:</td>
                                    <td>{{ loan.total_principal_paid }}</td>
                                </tr>
                                <tr>
                                    <td>Total Interest Paid:</td>
                                    <td>{{ loan.total_interest_paid }}</td>
                                    <td>Total Penalties Paid:</td>
                                    <td>{{ loan.total_penalties_paid }}</td>
                                </tr>
                                <tr>
                                    <td>Due Amount:</td>
                                    <td>{{ loan.due_amount }}</td>
                                    <td>Late Payment Penalties:</td>
                                    <td>{{ loan.late_payment_penalties }}</td>
                                </tr>
                                <tr>
                                    <td>First Payment Date:</td>
                                    <td>{{ loan.first_payment_date }}</td>
                                    <td>Release Date:</td>
                                    <td>{{ loan.release_date }}</td>
                                </tr>
                                <tr>
                                    <td>Approved Date:</td>
                                    <td>{{ loan.approved_date }}</td>
                                    <td>Approved By:</td>
                                    <td>{{ loan.approved_by }}</td>
                                </tr>
                                <tr>
                                    <td>Description:</td>
                                    <td>{{ loan.description }}</td>
                                    <td>Remarks:</td>
                                    <td>{{ loan.remarks }}</td>
                                </tr>
                            </tbody>
                        </table>
                      </div>
                    </div>                    
                </div>
            </div>

            <!-- Approval Tab -->
            <div class="tab-pane fade" id="approval" role="tabpanel" aria-labelledby="approval-tab">
                <div class="row mt-4">
                    <div class="col-md-6">
                        <h5>Loan Approval Details</h5>
                        <table class="table table-bordered">
                            <tbody>
                                <tr>
                                    <th scope="row">Approval Status</th>
                                    <td>{{ loan.status }}</td>
                                </tr>
                                <tr>
                                    <th scope="row">Approved By</th>
                                    <td>{{ loan.approved_by }}</td>
                                </tr>
                                <tr>
                                    <th scope="row">Approved Date</th>
                                    <td>{{ loan.approved_date }}</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    
                    {% if user_details.is_admin %}
                    <div class="col-md-6">
                        <!-- Add more approval details as needed -->
                        <h5>Approve/Reject Loan</h5>
                        <form method="post" action="{% url 'loan_approval' loan.id %}">
                            {% csrf_token %}
                        
                            <div class="mb-3">
                                <label for="id_approval_status" class="form-label">Approval Status:</label>
                                <div class="form-check">
                                    <input type="radio" name="approval_status" id="id_approval_status_approved" value="approved" class="form-check-input" {% if loan.status == 'approved' %}checked{% endif %} required>
                                    <label for="id_approval_status_approved" class="form-check-label">Approved</label>
                                </div>
                                <div class="form-check">
                                    <input type="radio" name="approval_status" id="id_approval_status_rejected" value="rejected" class="form-check-input" {% if loan.status == 'rejected' %}checked{% endif %} required>
                                    <label for="id_approval_status_rejected" class="form-check-label">Rejected</label>
                                </div>
                            </div>
                        
                            <div class="mb-3">
                                <label for="id_comments" class="form-label">Remarks:</label>
                                <textarea name="remarks" id="id_comments" class="form-control" rows="4" placeholder="Remarks">{% if loan.remarks %}{{ loan.remarks }}{% endif %}</textarea>
                            </div>
                        
                            <button type="submit" class="btn btn-primary">Submit Approval</button>
                        </form>
                        
                    </div>
                    {% endif %}
                </div>
            </div>

            <!-- Repayment Schedule tab -->
            <div class="tab-pane fade" id="collateral" role="tabpanel" aria-labelledby="collateral-tab">
                <div class="row mt-4">
                    <div class="col-md-12">
                        <h5>Repayment Schedule</h5>
                        {% if repayment_schedule %}
                      <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Installment Number</th>
                                    <th>Installment Date</th>
                                    <th>Principal Payment</th>
                                    <th>Interest Payment</th>
                                    <th>Remaining Balance</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for installment in repayment_schedule %}
                                    <tr>
                                        <td>{{ installment.installment_number }}</td>
                                        <td>{{ installment.installment_date }}</td>
                                        <td>{{ installment.principal_payment }}</td>
                                        <td>{{ installment.interest_payment }}</td>
                                        <td>{{ installment.remaining_balance }}</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                      </div>
                        {% else %}
                            <p>No repayment schedule available.</p>
                        {% endif %}
                    </div>
                </div>
        </div>

            <!-- Repayments Tab -->
            <div class="tab-pane fade" id="repayments" role="tabpanel" aria-labelledby="repayments-tab">
                <div class="row mt-4">
                    {% if user_details.is_admin %}
                    <div class="col-md-3">
                        <h5>Create Repayment  <br> Loan ID: {{ loan.id }}</h5>

                        <form method="post" action="{% url 'create_loan_repayment' loan.id %}">
                          {% csrf_token %}
                    
                          <div class="mb-3">
                            <label for="id_repayment_date" class="form-label">Repayment Date:</label>
                            <input type="date" name="repayment_date" id="id_repayment_date" class="form-control" required>
                          </div>

                          <div class="mb-3">
                            <label for="id_principal_paid" class="form-label">Principal Paid:</label>
                            <input type="number" name="principal_paid" id="id_principal_paid" class="form-control" step="0.01" required>
                          </div>
                    
                          <div class="mb-3">
                            <label for="id_interest_paid" class="form-label">Interest Paid:</label>
                            <input type="number" name="interest_paid" id="id_interest_paid" class="form-control" step="0.01" required>
                          </div>
                    
                          <div class="mb-3">
                            <label for="id_penalties_paid" class="form-label">Penalties Paid:</label>
                            <input type="number" name="penalties_paid" id="id_penalties_paid" class="form-control" step="0.01">
                          </div>
                    
    
                          <div class="mb-3">
                            <label for="id_remarks" class="form-label">Remarks:</label>
                            <textarea name="remarks" id="id_remarks" class="form-control" rows="4"></textarea>
                          </div>
                    
                          <button type="submit" class="btn btn-primary">Submit Repayment</button>
                        </form>
                    </div>
                    {% endif %}
                    <div class="col-md-9">
                        <h5>Repayment Details</h5>
                        {% if repayments %}
                        <table class="table">
                            <thead>
                              <tr>
                                <th>Repayment Date</th>
                                <th>Principal Paid</th>
                                <th>Interest Paid</th>
                                <th>Penalties Paid</th>
                                <th>Actions</th>
                              </tr>
                            </thead>
                            <tbody>
                              {% for repayment in repayments %}
                                <tr>
                                  <td>{{ repayment.repayment_date }}</td>
                                  <td>{{ repayment.principal_paid }}</td>
                                  <td>{{ repayment.interest_paid }}</td>
                                  <td>{{ repayment.penalties_paid }}</td>
                                  {% if user.is_authenticated %}
                                  <td>
                                      <a class="btn btn-danger btn-sm" href="{% url 'delete_repayment' loan_id=loan.id repayment_id=repayment.id %}">Delete</a>
                                  </td>
                              {% endif %}
                                </tr>
                              {% endfor %}
                            </tbody>
                          </table>
                        {% else %}
                            <p>No repayment details available.</p>
                        {% endif %}
                    </div>
                </div>
            </div>
    </div>
{% endblock %}